if Gem::Version.new(`pod --version`) >= Gem::Version.new('1.8.0')
    install! 'cocoapods',
    :generate_multiple_pod_projects => true,
    :incremental_installation => true
    else
    raise 'cocoapods required >= 1.8.0'
    return
end

`rm Podfile.lock`
use_frameworks!

platform :ios, '8.0'

target 'Taoprone_Example' do
  pod 'Taoprone', :path => '../'
  pod 'MLeaksFinder'
  pod 'React'

  target 'Taoprone_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
